#世代のlife cycleクラスが定義されているファイルの場所
#configディレクトリからの相対パスか、絶対パス
life_cycle_path: '../environment/life_cycle/simple_life_cycle.rb'

#使用するlifecycleクラス
life_cycle_class: 'GeneticAlgo::LifeCycle:::SimpleLifeCycle'

#世代数
generation: 100


#creatureクラスが定義されているファイルの場所
#configディレクトリからの相対パスか、絶対パス
creature_path: '../creature/origin_creature.rb'

#使用するcreatureクラス
creature_class: 'GeneticAlgo::Creature::OriginCreature'
#個体数
group_size: 50

#個体の遺伝子長
chromosome_size: 2

#個体の遺伝子の種類
#rangeオブジェクトでも可
gene_types: !ruby/range -100..100


#evalクラスが定義されているファイルの場所
#configディレクトリからの相対パスか、絶対パス
eval_path: '../environment/evaluation/evaluations/evaluator.rb'

#使用するevalクラスの指定
#Module.const_get　を使えば文字列でクラス指定ができるかもしれない
eval_class: 'TestEvaluator'

#selectクラスが定義されているファイルの場所
#configディレクトリからの相対パスか、絶対パス
select_path: '../environment/select/selects/roulette_select.rb'

#使用するselectクラス
select_class: 'RouletteSelect'
#選択が行われる際に選ばれる個体数
selected_group_size: 30

#crossoverクラスが定義されているファイルの場所
#configディレクトリからの相対パスか、絶対パス
crossover_path: '../environment/crossover/crossovers/uniform_crossover.rb'

#使用するcrossoverクラス
crossover_class: 'UniformCrossover'

#交叉に使用されるcreatureの数
crossover_convi_number: 2
#交叉が行われる確率
crossover_probability: 0.9
#交叉によって生成される個体数
crossover_group_size: 20


#mutationクラスが定義されているファイルの場所
#configディレクトリからの相対パスか、絶対パス
mutation_path: '../environment/mutation/mutations/random_mutation.rb'

#使用するmutationクラス
mutation_class: 'RandomMutation'
#突然変異がおこる確率
mutation_probability: 0.01
#突然変異する遺伝子の数
mutated_gene_number: 1
